import streamlit as st

st.markdown("""


### **Section 6.5 – Investment Income and Principal Protection**

1. All funds designated for member distributions and tax obligations shall be derived solely from dividends, interest, or other income generated by Trust investments.
    
2. The Trust shall maintain a separate bank account to which all investment income (including dividends and interest) shall be deposited directly.
    
3. No principal assets shall be liquidated or sold for the purpose of funding distributions or tax payments, except upon approval by a supermajority vote of the Voting-Eligible Members, and only when absolutely necessary.
    
4. Any sale of Trust holdings shall trigger an automatic Trust-wide alert, as per Section 8.11, detailing the nature, amount, and rationale for the transaction, along with the names of the Trustees initiating the sale.
    
5. Withdrawals from the investment account for purposes other than reinvestment or routine expenses shall be subject to prior member review and approval in accordance with Article VII.

---

### **6.6 Contributions and Investment Funding**

1. All new member contributions shall be initially deposited into the Trust’s designated bank account.
    
2. Contributions shall be transferred to the Trust’s investment account on a regular schedule, no less frequently than monthly, to enable timely investment of funds.
    
3. The Trustees shall oversee the timing and amounts of transfers to align with the Trust’s investment strategy and cash flow needs.
    
4. In exceptional circumstances, the Trustees may hold contributions in the bank account temporarily before transfer to maintain liquidity for pending distributions, tax payments, or administrative expenses.

---
### **3.2 - Opt-Out Provision**

- Any eligible member may **opt out** of participation.

- Opting Out forfeits any and all benefits, including, but not limited to receiving distributions, voting rights, access to LLC owned properties.
            
            """)